authts/react-oidc-context

.gitignore
api-extractor.json
dist/esm/package.json
package.json
scripts/build.js

Workaround for react-scripts incompatibility with .mjs resolution

---

README.md
docs/react-oidc-context.api.md
src/AuthProvider.tsx
src/AuthState.ts
src/index.ts
src/reducer.ts
test/AuthProvider.test.tsx

Add activeNavigator prop

---

.github/pull_request_template.md
.husky/pre-commit

- copied from your commit in  oidc-client-ts
- i was first skeptical with re-basing, but turns out its works nicely too. i started to really like that feature :-)

chore: update API report on pre-commit

---

README.md
docs/react-oidc-context.api.md
src/AuthContext.ts
src/AuthProvider.tsx

Events part of #239 
I would appreciate if the you could make the deprecation. Each deprecation must come with a
replacement code instruction, which i have not looked up yet...

expose events in api

---

README.md

fix: #251 improve install instructions

---

README.md
example/index.tsx

fix: eslint-plugin 5.13.0 errors

---

package-lock.json
package.json

chore: drop unused @testing-library/react-hooks

---

.github/workflows/ci.yml
.gitignore
example/index.html
example/package-lock.json
example/package.json

fix build error of example project

---

README.md

document automatic sign-in

---

.github/workflows/ci.yml
.github/workflows/release.yml

bump actions and codecov-action to v3

ci: bump actions

---

package.json

Add "types" path to exports

---

src/AuthProvider.tsx

properly await onSigninCallback, which potentially can return a promise

---

README.md

Closes/fixes --
Just minor fixes to make the code valid right away.

Fix protected API example

---

README.md

Hi and thank you for making this library.
While setting it up on my project, I encountered a few issues, notably an infinite loop, which I'm fixing in this PR.
Also, automatically reestablishing the user session only works if we configure `localStorage` as the `userStore`, but this is not mentioned in the code example, so I'm fixing that as well.
---
Here the detail of the commits:
The code example for `Automatic sign-in` was creating an infinite loop triggering hundreds of signin requests per seconds when the network was unreachable.
The reason is that `auth.signingRedirect()` changes the state of `auth.isLoading`; then, when the request fails because the user is offline, `auth.isLoading` changes again, triggering `auth.signinRedirect()`.
to prevent `Unable to log in` from being visible …

doc(readme): Fix auto signin issues

---

docs/react-oidc-context.api.md
src/AuthProvider.tsx
test/AuthProvider.test.tsx

drop deprecated code

---

README.md

Fix useState statement on Automatic sign-in section of Readme.md

---

README.md

docs: Insert yarn installation step inside README.md

---

src/AuthProvider.tsx

remove now useless useCallback on signoutSilent

---

src/AuthProvider.tsx

Closes/fixes #972
@PSanetra i missed "remove the event when destroy" in review, here it comes...

add removeUserSignedOut when destroy

---

src/AuthProvider.tsx
src/utils.ts
test/AuthProvider.test.tsx

Improve unit tests

---

README.md

OnRedirecting vs. onRedirecting

---

src/AuthProvider.tsx
test/AuthProvider.test.tsx

memoize context value in auth-provider

---

.github/workflows/ci.yml
.github/workflows/release.yml

use node 18.x, prepare publish to previous tag

---

example/package-lock.json
example/package.json
package-lock.json
package.json

bump typescript from 5.4.5 to 5.7.3

---

.github/workflows/ci.yml
.github/workflows/release.yml

update pipeline to node 20
