authts/react-oidc-context

package-lock.json, src/AuthProvider.tsx
Hey, I see things are in flux here with the `oidc-client-ts` migration, hopefully it's ok that this targets the `main` branch.
This PR fixes SSR by condtitionally creating a UserManager instance based on the presence of `window`. The context API is preserved since I replace all userManager actions with a no-op function that throws when called.
This doesn't change existing client-side behavior to my knowledge.
=> support rendering AuthProvider server-side

src/AuthProvider.tsx, test/AuthProvider.test.tsx, test/__mocks__/oidc-client.ts
This is building off of the SSR support from earlier - I've added an optional `implementation` prop to `AuthProvider`. In a browser environment with `window`, the default value is the out-of-the-box `UserManager` class from oidc-client.
This approach allows someone to build a custom `UserManager` class that supports a server-side environment. I also have a use case where I want to do some preprocessing in the `*Callback()` functions before I hand off to UserManager.
=> feat: Support passing a custom UserManager implementation

package-lock.json, package.json
Technically 2.0.0-rc.4 is same as 2.0.0
=> build: bump oidc-client-ts from 2.0.0-rc.4 to 2.0.0

src/AuthProvider.tsx, test/AuthProvider.test.tsx, test/helpers.tsx
Ensure parsing the `window.location` is only done once, when using `React.StrictMode`.
~~I am not 100% sure if we need the additional guard for the event registering at all.~~
For event registering the cleanup function takes care...
Unit tests: The new test case uses `@testing-library/react`, which is the new way to test. The other test cases still use `@testing-library/react-hooks`, which should a some point be ported too. Not urgent and not in this MR. Just a technical dept (#433).
Closes/fixes #401
Fix according do documentation: https://github.com/reactwg/react-18/discussions/18
=> make sure signinCallback is only called once in React.StrictMode

src/AuthProvider.tsx, test/AuthProvider.test.tsx, test/helpers.tsx, test/useAuth.test.tsx
Closes/fixes: [#431](https://github.com/authts/react-oidc-context/issues/433).
This PR is a follow-up of the [PR #421](https://github.com/authts/react-oidc-context/pull/421), in which was decided that it would be nice to refactor all tests to use the `@testing-library/react` exclusively.
=> refactor: use renderHook from @testing-library/react

src/AuthProvider.tsx, test/AuthProvider.test.tsx
USER_LOADED event sets the right user.state, but INITIALISED event will reset user.state  to undefined, use signinCallback user to set state to solve the issue
Closes/fixes #issue
=> fix error when user.state is set to undefined.

src/useAuth.ts, test/useAuth.test.tsx
resolves #855
instead of letting useAuth throw if there is no provider, allow to not wrap the parent(s) with the provider, to make the oauth config dynamic and allow it to lazy load later. in consumer code, just check that the value of useAuth is not undefined.
this allows an app to have different oauth configs depending on the runtime without having to "remove" all useAuth usages if there is no provider yet.
fyi it seems the old test for checking the exception was not working (no fail after removing the exception).
=> useAuth should not throw

README.md
I fixed the broken link for LICENSE in README.
=> doc(readme): Fix broken link for LICENSE

docs/react-oidc-context.api.md, src/AuthContext.ts, src/AuthProvider.tsx, src/AuthState.ts, test/AuthProvider.test.tsx, test/__mocks__/oidc-client-ts.ts
I added the signinResourceOwnerCredentials method in AuthContextProps for [Resource Owner Password Credentials Grant]() in OAuth2.0.
=> feat: add signinResourceOwnerCredentials

docs/react-oidc-context.api.md, src/AuthProvider.tsx
Follow up of #466, which only covered some properties of `UserManagerSettings`. Where this MR splits `AuthProviderNoUserManagerProps` and AuthProviderUserManagerProps for all relevant properties. #466 was type-wise a breaking change, thus the next release will bump to 3.0.0.
Closes/fixes #issue
=> AuthProviderUserManagerProps must not contain anything from UserManagerSettings

README.md, docs/react-oidc-context.api.md, src/index.ts, src/withAuthenticationRequired.tsx, test/withAuthenticationRequired.test.tsx
Closes/fixes #issue
Heavy inspired by auth0 code found here https://github.com/auth0/auth0-react/blob/main/src/with-authentication-required.tsx
=> feat: add withAuthenticationRequired

.gitignore, src/AuthProvider.tsx, src/reducer.ts
We experienced the same issue like #972 and as far as I see this is caused by the currently unhandled userSignedOut event.
Fixes #972
=> fix: Handle USER_SIGNED_OUT event the same like USER_UNLOADED

.github/workflows/ci.yml, docs/react-oidc-context.api.md, src/AuthProvider.tsx, src/utils.ts, test/AuthProvider.test.tsx, test/SSR.test.tsx, test/__mocks__/oidc-client-ts.ts
=> logout callback support

docs/react-oidc-context.api.md, src/AuthProvider.tsx
=> pass signoutCallback reponse to onSignoutCallback

src/AuthProvider.tsx, test/AuthProvider.test.tsx
Backport fix: #1357 memoize context value in auth-provider
=> backport memoize context value in auth provider

README.md, docs/react-oidc-context.api.md, src/index.ts, src/withAuthenticationRequired.tsx, test/withAuthenticationRequired.test.tsx
backport feat: #1060 add with authentication required
=> backport add with authentication required

docs/react-oidc-context.api.md, package-lock.json, package.json, src/AuthProvider.tsx, src/utils.ts, test/AuthProvider.test.tsx, test/__mocks__/oidc-client-ts.ts
(cherry picked from commit 210f1c0fbad7070d4da0c4f5e0dafe24ea11f8a9)
=> backport on signout callback

src/AuthProvider.tsx, src/reducer.ts
backport #1087: handle USER_SIGNED_OUT (session monitoring event) event the same like USER_UNLOADED
(cherry picked from commit fa99ee20d8cd7f87c90523626960359387672450)
=> backport handle USER_SIGNED_OUT event the same like USER_UNLOADED

docs/react-oidc-context.api.md, src/AuthProvider.tsx, src/withAuthenticationRequired.tsx, test/helpers.tsx, test/withAuth.test.tsx, test/withAuthenticationRequired.test.tsx
=> use React.JSX instead of the global JSX namespace

package.json
See https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
=> new JSX transform needs at least React v16.14.0

README.md, docs/react-oidc-context.api.md, example/index.tsx, src/AuthProvider.tsx, src/AuthState.ts, src/index.ts, src/reducer.ts, src/utils.ts, test/AuthProvider.test.tsx
This added `AuthState.errorContext: ErrorContext` which holds information what was causing the issue. Most likely which method and (if available) the provided `args`.
=> Added `ErrorContext` to give more context which action caused the actual error.
